language: node_js
sudo: false
node_js: 4
env:
 - LINT=
 - LINT=1
addons:
  apt:
    packages:
     - python3.5
install:
 - npm install node-qunit-phantomjs
 - npm install jshint
before_script:
 - python3 -m tests.server &
script:
 - ./runtests.sh
