language: node_js
sudo: false
node_js: 4
env:
 - LINT=
 - LINT=1
addons:
  apt:
    packages:
     - python3
install:
 - npm install https://github.com/sheppard/node-qunit-phantomjs/tarball/patch-1
 - npm install jshint
before_script:
 - python3 setup.py test
 - PYTHONPATH=`html_json_forms*egg` python3 -m tests.server &
 - cd tests
 - wq collectjson
 - cd ..
script:
 - ./runtests.sh
