dist: xenial
language: node_js
node_js: 11
install:
 - make js_build
script:
 - python3 -m tests.server &
 - ./runtests.sh
matrix:
  include:
    - name: "@wq/app"
      env: PACKAGE=app
    - name: "@wq/chart"
      env: PACKAGE=chart
    - name: "@wq/jest-env-jsdom-idb"
      env: PACKAGE=jest-env-jsdom-idb
    - name: "@wq/jquery-mobile"
      env: PACKAGE=jquery-mobile
    - name: "@wq/map"
      env: PACKAGE=map
    - name: "@wq/markdown"
      env: PACKAGE=markdown
    - name: "@wq/model"
      env: PACKAGE=model
    - name: "@wq/outbox"
      env: PACKAGE=outbox
    - name: "@wq/router"
      env: PACKAGE=router
    - name: "@wq/store"
      env: PACKAGE=store
    - name: "@wq/template"
      env: PACKAGE=template
    - name: "wq.app PyPI Package"
      language: python
      python: 3.7
      install:
        - pip install --upgrade pip
        - make
        - pip install .
      script:
        - cd tests
        - mkdir css && wq init && wq scss --indir scss --outdir css
        - cd commands;
        - ./test_commands.sh
    - name: "JavaScript Lint"
      install: npm install
      script: npm run lint
    - name: "Python Lint"
      language: python
      python: 3.7
      install: pip install flake8
      script: flake8 build/*.py
